{dependency name="utils.math"}
{dependency name="ui.button"}
{dependency name="ui.toolbox"}
{dependency name="graphics"}
{dependency name="graphics.tests"}
{dependency name="floorplan"}
{dependency name="floorplan.tools"}
{dependency name="floorplan.things"}
{dependency name="space.three"}
<div data-elation-component="floorplan"></div>
{set var="page.title"}Floorplan Editor{/set}
